RuntimeError: C/C++ floating-point exception. doesn't exist anymore
git-svn-id: http://svn.code.sf.net/p/cctbx/code/trunk@6579 3c1a6239-ac2c-0410-bc49-92500e444112